export const site = { name: 'Peake Property Solutions', url: 'https://peake-ps.vercel.app', phone: '(410) 924-4020', phoneHref: 'tel:+14109244020', email: 'peakepropertysolutions@gmail.com', facebook: 'https://www.facebook.com/people/Peake-Property-Solutions/61576335597016/' };

export const services = [
  { slug: 'landscaping', name: 'Landscaping', summary: 'Thoughtful landscape work that brings order, curb appeal, and a better sense of place to the spaces around your property.', when: ['An outdoor area feels unfinished or disconnected from the way you live.', 'You want a clearer, more considered first impression.', 'You need hands-on local help moving an outdoor improvement forward.'], outcomes: ['A more intentional, usable outdoor space', 'Clear communication around your property priorities', 'A clean finish that respects the rest of the property'], faqs: [['Do you provide landscaping across the Eastern Shore?', 'Yes. Peake Property Solutions is based in Hurlock and serves communities across Maryland’s Eastern Shore, including Cambridge, Denton, Easton, Saint Michaels, and Salisbury.'], ['How do I request a landscaping quote?', 'Call, text, or email with your property city, a short description of the outdoor work you have in mind, and any useful photos.']] },
  { slug: 'hardscaping', name: 'Hardscaping', summary: 'Practical hardscape improvements designed around the way you use and move through your outdoor space.', when: ['You want outdoor details that feel more finished and useful.', 'A patio, edge, walk, or exterior area needs more structure.', 'You are pairing a landscape refresh with lasting exterior improvements.'], outcomes: ['More useful outdoor areas', 'A finished look that complements the property', 'A local conversation about the right next step'], faqs: [['What hardscape work can I ask Peake about?', 'Peake Property Solutions provides landscape and hardscape services. Share your outdoor goals and property location to discuss whether the project is a fit.'], ['Do I need a complete design before I call?', 'No. Start with how you use the space today and what you would like it to do better. A practical conversation can help clarify the next step.']] },
  { slug: 'property-cleanups', name: 'Property Cleanups', summary: 'A fresh, practical reset for outdoor areas that need attention before they can feel clear, usable, and manageable again.', when: ['An outdoor area has fallen behind and feels hard to tackle.', 'You want to prepare a property for a season, sale, or next improvement.', 'You need a clean starting point before deciding what comes next.'], outcomes: ['A visibly cleaner outdoor area', 'A clearer view of the property’s opportunities', 'Less stress around a long-postponed outdoor task'], faqs: [['What should I include in a cleanup quote request?', 'Include the property city, the outdoor area that needs attention, what you have noticed, and what you want the space to feel like afterward.'], ['Can a cleanup come before landscaping?', 'Yes. A cleanup often makes it much easier to see the property clearly and decide which landscaping or hardscape improvements make sense next.']] },
  { slug: 'overgrowth-transformations', name: 'Overgrowth Transformations', summary: 'Hands-on resets for outdoor spaces that have gotten away from you and need to become visible, approachable, and manageable again.', when: ['Growth is making parts of the property hard to access.', 'You can no longer see the condition or potential of an outdoor area.', 'A small task has become an intimidating project.'], outcomes: ['A space you can see and evaluate again', 'A practical reset instead of an open-ended to-do list', 'A cleaner base for future care or improvements'], faqs: [['Do you work with seriously overgrown properties?', 'Yes. Overgrowth transformations and property cleanups are central Peake Property Solutions services. Reach out with the location and condition of the space.'], ['What happens after an overgrowth reset?', 'Once the space is clear and visible, it is easier to decide what maintenance, landscaping, or hardscape work should come next.']] },
];

export const cities = [
  ['hurlock-md', 'Hurlock', 'Dorchester County', 'Based in Hurlock, Peake Property Solutions provides local landscaping, hardscaping, property cleanups, and overgrowth transformations for Eastern Shore properties.', 38.6337, -75.8622],
  ['cambridge-md', 'Cambridge', 'Dorchester County', 'Peake Property Solutions serves Cambridge property owners looking for practical landscaping, outdoor cleanup, and exterior improvements.', 38.5726, -76.0788],
  ['denton-md', 'Denton', 'Caroline County', 'Denton property owners can contact Peake Property Solutions for hands-on landscape, hardscape, cleanup, and overgrowth work.', 38.8846, -75.8272],
  ['easton-md', 'Easton', 'Talbot County', 'Peake Property Solutions helps Easton homeowners and property owners make outdoor spaces cleaner, more useful, and ready for the next step.', 38.7743, -76.0763],
  ['saint-michaels-md', 'Saint Michaels', 'Talbot County', 'Peake Property Solutions brings reliable landscaping, hardscaping, cleanup, and outdoor property support to Saint Michaels and nearby Eastern Shore communities.', 38.7851, -76.2230],
  ['salisbury-md', 'Salisbury', 'Wicomico County', 'Salisbury property owners can reach Peake Property Solutions for practical outdoor improvements, property cleanups, and overgrowth transformations.', 38.3607, -75.5994],
].map(([slug, name, county, intro, latitude, longitude]) => ({ slug, name, county, intro, latitude, longitude }));

export const blogs = [
  ['eastern-shore-property-cleanup-checklist', 'An Eastern Shore Property Cleanup Checklist for a More Manageable Yard', 'Property Cleanups', 'A practical property cleanup checklist for Eastern Shore homeowners who need a clear place to start.', 'Start with the areas you use most', 'Walk the property and identify the places that affect daily life first: entrances, paths, patios, driveway edges, and spaces where growth or debris gets in the way.', 'Separate a reset from a wish list', 'The first goal is to make the space visible and manageable. Once it is cleared, it is easier to decide which landscape or hardscape improvement matters most.'],
  ['signs-your-yard-needs-an-overgrowth-reset', '5 Signs Your Yard Needs an Overgrowth Reset', 'Overgrowth', 'Know when an overgrown outdoor area has reached the point where a focused reset can make the biggest difference.', 'Loss of access is a clear signal', 'When growth makes paths, edges, or parts of the yard difficult to reach, the task has moved beyond a small weekend project.', 'Visibility changes the conversation', 'A reset can reveal the condition and potential of the property, making maintenance and improvement choices much easier.'],
  ['how-to-prepare-for-a-landscape-cleanup', 'How to Prepare for a Landscape Cleanup Before Requesting a Quote', 'Planning', 'Simple preparation steps that help an Eastern Shore property cleanup quote start with the right information.', 'Define the result you want', 'A useful request says more than what is wrong. It also identifies whether you want clearer access, a cleaner first impression, or a fresh starting point.', 'Gather a few useful details', 'The city, area condition, access notes, and a few photos can make a first conversation more productive.'],
  ['landscape-maintenance-vs-property-cleanup', 'Property Cleanup vs. Ongoing Outdoor Care: What Is the Difference?', 'Property Care', 'Understand the difference between resetting an outdoor space and keeping it more manageable after the reset.', 'A cleanup creates a baseline', 'Property cleanups are focused resets for areas that need visible, hands-on attention before they are easy to manage again.', 'Care protects the progress', 'Once the space is in better shape, regular attention can help prevent the same outdoor challenge from becoming overwhelming again.'],
  ['spring-yard-reset-eastern-shore-md', 'A Practical Spring Yard Reset for Maryland’s Eastern Shore', 'Seasonal Care', 'Use this spring yard reset guide to focus outdoor attention where it can have the strongest practical effect.', 'Walk the property after winter', 'Early spring can make it easier to spot neglected edges, difficult access, and spaces that no longer support how you use the outdoors.', 'Reset before you refine', 'Address the areas that make the property feel overwhelming before moving to smaller polish or planting decisions.'],
  ['fall-property-cleanup-guide-maryland', 'A Fall Property Cleanup Guide for Maryland Homeowners', 'Seasonal Care', 'A straightforward fall cleanup guide for homeowners preparing outdoor spaces for a new season.', 'Protect the areas you rely on', 'Entrances, walkways, and outdoor gathering spaces deserve attention first because they shape how easily you use the property as conditions change.', 'Do not carry overgrowth forward', 'An area that is already difficult to manage rarely becomes easier after more time passes. A fall reset can create a better starting point for spring.'],
  ['curb-appeal-starts-with-a-clean-property', 'Why Curb Appeal Starts With a Clean, Manageable Property', 'Landscaping', 'Before planning upgrades, give the property a clean foundation for meaningful outdoor change.', 'You have to see the space to improve it', 'Growth, clutter, and neglected outdoor areas can hide the property’s lines and potential. Cleanup restores visibility.', 'Focus on the first impression', 'The entrance, driveway edge, and visible outdoor areas can make the entire property feel more cared for.'],
  ['questions-to-ask-before-hiring-landscaper', 'Questions to Ask Before Hiring Local Landscaping Help', 'Planning', 'A useful checklist for Eastern Shore property owners comparing local landscape and hardscape providers.', 'Ask about the property outcome', 'A productive first conversation connects the work to a real result: better access, a cleaner area, more useful outdoor space, or a stronger first impression.', 'Confirm how scope will be discussed', 'Clear communication about the area, condition, access, and priorities helps everyone begin with the same understanding.'],
  ['how-to-prioritize-large-yard-cleanup', 'How to Prioritize a Large Yard Cleanup Without Feeling Overwhelmed', 'Property Cleanups', 'Break a large outdoor cleanup into practical priorities and choose a sensible first step.', 'Start with function', 'Look for the outdoor areas that are hardest to use now. If growth or debris affects how you enter, walk through, or enjoy the property, start there.', 'Work in visible zones', 'A large property becomes more manageable when divided into areas such as the front approach, side yard, rear space, or perimeter.'],
  ['what-to-do-with-an-overgrown-outdoor-space', 'What to Do When an Outdoor Space Has Become Overgrown', 'Overgrowth', 'A first-step guide for homeowners facing an overgrown yard or neglected exterior area.', 'Recognize the real first step', 'When a space has become overgrown, planning the perfect final landscape can wait. Regaining sightlines, access, and a sense of control comes first.', 'Choose the next right-size project', 'After the reset, identify one useful improvement or care habit so the transformation remains practical.'],
  ['eastern-shore-homeowner-outdoor-maintenance-calendar', 'An Outdoor Property Care Calendar for Eastern Shore Homeowners', 'Property Care', 'A season-by-season framework for keeping outdoor needs from piling up.', 'Spring is for noticing and resetting', 'Use the beginning of the growing season to spot neglected areas and handle the cleanups that will make the rest of the year easier.', 'Keep a short priority list', 'A simple list of outdoor tasks helps turn a future quote request into a clearer, more useful conversation.'],
  ['first-time-homeowner-yard-checklist', 'A First-Time Homeowner’s Yard and Outdoor Property Checklist', 'Homeowner Guide', 'A clear checklist for new homeowners who want to understand their outdoor property before making changes.', 'Walk the whole exterior', 'A slow walk around the property can uncover immediate needs such as overgrowth, blocked access, and spaces that will be difficult to maintain.', 'Separate needs from ideas', 'A cleanup or practical reset may be more urgent than a future upgrade. Listing both helps you choose what to handle first.'],
  ['how-to-plan-outdoor-property-improvement', 'How to Plan an Outdoor Property Improvement in Three Practical Steps', 'Planning', 'Move from an outdoor property problem to a clear, manageable improvement plan.', 'Describe the condition you have', 'Start with what is really happening: a neglected area, limited access, overgrowth, or an outdoor space that does not feel finished.', 'Decide what better looks like', 'Good planning is outcome-based. It might mean a clean entry, more usable outdoor space, or a property that feels cared for again.'],
  ['landscaping-for-a-more-usable-outdoor-space', 'Landscaping for a More Usable Outdoor Space: Start With How You Live', 'Landscaping', 'A homeowner-focused way to think about outdoor work that supports everyday use.', 'Start with daily patterns', 'Consider how you arrive, where you walk, what you see first, and which outdoor areas you would like to use more often.', 'Keep the first project focused', 'A single thoughtful improvement can have more impact than a broad plan that never gets started.'],
  ['when-to-request-property-cleanup-quote', 'When Is the Right Time to Request a Property Cleanup Quote?', 'Property Cleanups', 'You do not need a perfect plan before asking for help with an outdoor property cleanup.', 'Reach out when the work affects daily use', 'A quote conversation makes sense when an outdoor area is keeping you from accessing, using, or enjoying part of the property.', 'A clear goal is enough to begin', 'Share the city, the area that needs attention, and the result you are after. That is enough to start a practical conversation.'],
  ['prepare-property-for-easier-outdoor-care', 'How to Prepare Your Property for Easier Outdoor Care', 'Property Care', 'Use a cleanup and realistic priorities to make ongoing outdoor care feel less overwhelming.', 'Start with a clean baseline', 'It is easier to care for a property once neglected areas have been addressed. A reset makes the rest of the work feel more achievable.', 'Notice repeat trouble spots', 'Think about the locations that fall behind first. Naming them helps you focus attention where it matters most.'],
  ['clean-up-before-selling-your-home', 'Why an Outdoor Property Cleanup Matters Before Selling a Home', 'Homeowner Guide', 'A clean, visible exterior can help homeowners present a property with more confidence before a sale.', 'First impressions start before the door', 'A clean entrance and manageable outdoor space can make a property feel more cared for from the first approach.', 'Let viewers see the property', 'Neglected growth can obscure the size, shape, and potential of exterior spaces. Cleanup helps people understand what is there.'],
  ['local-landscaping-hurlock-eastern-shore', 'What to Look For in Local Landscaping Help on Maryland’s Eastern Shore', 'Local Guide', 'Choose local outdoor-property help by focusing on clear communication, practical scope, and service-area fit.', 'Start with service-area fit', 'Share your city at the beginning of the conversation. Location, access, and the condition of the space are all useful details.', 'Value a practical first step', 'The best first action is usually the one that makes your property more usable and manageable right away.'],
].map(([slug, title, category, description, heading1, copy1, heading2, copy2]) => ({ slug, title, category, description, heading1, copy1, heading2, copy2 }));
